stages:
  - build
  - test
minimum:
  stage: build
  tags:
    - clang7
  script:
    - curl -OLs https://teaching.ethanmiller.org/gitlab-testing/check_submission && python3 check_submission https://users.soe.ucsc.edu/~atbarker/check_submissions-13s.toml
  artifacts:
    expire_in: 1 week
functional_test:
  stage: test
  tags:
    - clang7
  script:
    - curl -OLs https://teaching.ethanmiller.org/gitlab-testing/check_submission && python3 check_submission https://users.soe.ucsc.edu/~atbarker/check_submissions-13s.toml test
  when:  manual
~  
